spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-round-mountain-apz8t2t3-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_GLNokF2W7MHX}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8080}
